export * from 'coco-ioc-container';
export * from 'coco-reactive';
export * from 'coco-router';
export { default as Bind } from './metadata/bind.ts';
export { default as bind } from './decorator/bind.ts';
export { default as Controller } from './metadata/controller.ts';
export { default as controller } from './decorator/controller.ts';
export { default as GlobalData } from './metadata/global-data.ts';
export { default as globalData } from './decorator/global-data.ts';
export { default as Ref } from './metadata/ref.ts';
export { default as ref } from './decorator/ref.ts';
export { default as Refs } from './metadata/refs.ts';
export { default as refs } from './decorator/refs.ts';
export { default as Service } from './metadata/service.ts';
export { default as service } from './decorator/service.ts';
export { default as View } from './metadata/view.ts';
export { default as view } from './decorator/view.ts';
export { default as WebApplication } from './metadata/web-application.ts';
export { default as webApplication } from './decorator/web-application.ts';
export { default as Render } from './component/render.ts';
export { default as WebRender } from './render/web-render.ts';

export * from './_test_helper';
