name: Publish

on:
  push:
    tags:
      - 'v0.0.1-alpha*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Install pnpm
        run: npm install -g pnpm@8.6.2

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Add Npm Token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - name: Publish coco-mvc
        working-directory: packages/coco-mvc
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @cocojs/cli
        working-directory: packages/coco-cli
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
